# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: James Turner <james@flightgear.org>

spec:
  inputs:
    clear-ccache-cache:
      type: boolean
      default: false
      description: "Clear the 'ccache' cache before starting the builds"
---

variables:
  BUILD_DIR: "$CI_PROJECT_DIR/build"
  PREFIX_DIR: "$CI_PROJECT_DIR/simgear-dist"
  # create a root dir *above* the Simgear checkout, otherwise CMake
  # complains about INTERFACE_INCLUDE_DIRECTORIES being the source dir
  WIN_FG_DIR: $CI_BUILDS_DIR\flightgear
  MAC_IMAGE: macos-14-xcode-15
  OSG_REF: next
  # cache:key is not allowed to contain '/' characters
  BRANCH_REF_SLUG: next
  HOMEBREW_NO_AUTO_UPDATE: 1
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

# do not run pipelines on forks
# build merge requests, tags and the protected branches
workflow:
  rules:
    - if: $CI_PROJECT_NAMESPACE != "flightgear"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

# There is an example at https://pre-commit.com/#gitlab-ci-example
.pre-commit-common:
  stage: build
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/pre-commit:latest
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    key: pre-commit
    paths:
      - ${PRE_COMMIT_HOME}

# This job runs only on MR branches and needs to pass.
pre-commit-merge:
  extends: .pre-commit-common
  script:
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - >
      pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      --to-ref "$CI_COMMIT_SHA"
    - git-clang-format --diff origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pre-commit:
  extends: .pre-commit-common
  script:
    # Run on all files. We're quite far from this being error-free, so report
    # success despite reality. This way, the pipeline status can be used to
    # monitor jobs we're actively trying to keep in working state.
    - pre-commit run --all-files || true
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.ccache-variables:
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/ccache-cache
    # This allows one to obtain ccache stats for a single job.
    CCACHE_STATSLOG: ${CI_PROJECT_DIR}/ccache-stats.log

.ccache-pre_non-windows:
  before_script:
    # Optional clearing of the 'ccache' cache
    - |
      if $[[ inputs.clear-ccache-cache ]]; then
        echo "Clearing the 'ccache' cache"
        ccache --clear
      fi
    - rm -f $CCACHE_STATSLOG

.ccache-pre_windows:
  before_script:
    # Optional clearing of the 'ccache' cache
    - |
      if ('$[[ inputs.clear-ccache-cache ]]' -eq 'true') {
        echo 'Clearing the ''ccache'' cache'
        ccache --clear
      }
    - |
      if (Test-Path $CCACHE_STATSLOG) {
        Remove-Item -Path $CCACHE_STATSLOG
      }

.ccache-stats:
  after_script:
    # For the particular build recorded in ${CCACHE_STATSLOG}
    - ccache --show-log-stats
    # Shows how much of the configurable cache size is used
    - ccache --show-stats

linux-build:
  extends: .ccache-variables
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear:latest
  stage: build
  before_script:
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    - rm -f $BUILD_DIR/CMakeCache.txt
    # --fresh would be ideal here
    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_PREFIX_PATH=$CI_PROJECT_DIR/osg-dist
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $OSG_REF
      artifacts: true
  artifacts:
    when: on_success
    paths:
      - $PREFIX_DIR
      # This is needed for the 'test' job.
      - $BUILD_DIR
    exclude:
      - $BUILD_DIR/3rdparty/
      - $BUILD_DIR/CMakeFiles/
      - $BUILD_DIR/**/*.h
      - $BUILD_DIR/**/*.hxx
      - $BUILD_DIR/**/*.o
      - $BUILD_DIR/**/*.a
      - $BUILD_DIR/.ninja_*
      - $BUILD_DIR/build.ninja
  cache:
    key: linux-amd64-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

# even though Simgear doesn't use Qt5, we make some other changes in this image,
# such as using a different C-Ares version, which mean we need a distinct Simgear build,
# to match the FlighGear build
linux-qt5-build:
  extends: .ccache-variables
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear-qt5:latest
  stage: build
  before_script:
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    - rm -f $BUILD_DIR/CMakeCache.txt
    # --fresh would be ideal here to avoid the line above, but needs CMake 3.25
    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_PREFIX_PATH=$CI_PROJECT_DIR/osg-dist
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $OSG_REF
      artifacts: true
  artifacts:
    paths:
      - $PREFIX_DIR
  cache:
    key: linux-amd64-qt5-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

windows-build:
  stage: build
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}\ccache-cache
    CCACHE_STATSLOG: ${CI_PROJECT_DIR}\ccache-stats.log
  tags:
    - saas-windows-medium-amd64
  before_script:
    - C:\"Program Files (x86)\Microsoft Visual Studio"\2022\BuildTools\Common7\Tools\Launch-VsDevShell -SkipAutomaticLocation -Arch amd64
    - cmake --version
    - ninja --version

    # relocate our upstream deps outside the source dir, otherwise
    # CMake gets sad.
    - Move-Item -Path $CI_PROJECT_DIR\boost $WIN_FG_DIR\boost
    - Move-Item -Path $CI_PROJECT_DIR\msvc140 $WIN_FG_DIR\msvc140
    # This is for ccache.exe.
    - $Env:PATH += ";$CI_PROJECT_DIR"
    - !reference [.ccache-pre_windows, before_script]
  script:
    - >
      cmake -B $env:BUILD_DIR -S $env:CI_PROJECT_DIR -G "Ninja Multi-Config"
      --fresh
      -D CMAKE_INSTALL_PREFIX=$env:PREFIX_DIR
      -D CMAKE_PREFIX_PATH=$env:CI_PROJECT_DIR/osg-dist
      -D MSVC_3RDPARTY_ROOT=$WIN_FG_DIR
      -D OSG_FSTREAM_EXPORT_FIXED:BOOL=ON
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR --config Release
    - cmake --build $BUILD_DIR --config Release --target install
  after_script:
    # This is needed for ccache.exe.
    - $Env:PATH += ";$CI_PROJECT_DIR"
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/openscenegraph
      job: windows_build
      ref: $OSG_REF
      artifacts: true
    - project: flightgear/windows-3rd-party
      job: windows_build_msvc140
      ref: master
      artifacts: true
  artifacts:
    paths:
      - $PREFIX_DIR
  cache:
    key: windows-amd64-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

macos-build:
  stage: build
  extends: .ccache-variables
  tags:
    - saas-macos-medium-m1
  image: $MAC_IMAGE
  before_script:
    - export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
    - export HOMEBREW_NO_INSTALL_CLEANUP=1
    - brew install ninja cmake boost c-ares ccache
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja --fresh
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_PREFIX_PATH="$CI_PROJECT_DIR/osg-dist;$CI_PROJECT_DIR/dist"
      -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      -D ENABLE_SIMD=OFF
      -D ENABLE_VIDEO_RECORD:BOOL=OFF
      -D ENABLE_CCACHE=ON
      -D ENABLE_TESTS:BOOL=OFF # BoostTest isn't build fat, so we need to disable tests on macOS : ho-hum.

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/openscenegraph
      job: macos-build
      ref: $OSG_REF
      artifacts: true
    - project: flightgear/macos-3rd-party
      job: macos-build
      ref: main
      artifacts: true
  artifacts:
    paths:
      - $PREFIX_DIR
  cache:
    key: macos-universal-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

# Run tests using the binaries from the 'linux-build' job.
test:
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear:latest
  stage: test
  needs:
    # Needed so we have the OSG libs
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $OSG_REF
      artifacts: true
    - job: linux-build
      artifacts: true
  script:
    - cd $BUILD_DIR
    # Some tests need the OSG libraries.
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CI_PROJECT_DIR/osg-dist/lib
    - ctest --output-on-failure --output-junit result.xml
  artifacts:
    # Note that the artifacts in artifacts:reports are _always_ uploaded,
    # even for failed jobs (special rule).
    paths:
      - $BUILD_DIR/result.xml
    reports:
      junit: $BUILD_DIR/result.xml

# if we're building a merge request, build the corresponding
# target branch of FlightGear. This assumes that target
# branches are identical for SimGear+FlightGear
staging:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  trigger:
    project: flightgear/flightgear
    branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    strategy: depend
  inherit:
    variables: false

# if we're NOT building a merge-request, build the
# same branch as here: again this assumes SimGear+FlightGear
# branches names match
staging:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event'
  trigger:
    project: flightgear/flightgear
    branch: $CI_COMMIT_BRANCH
    strategy: depend
  inherit:
    variables: false
