# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2025 James Turner <james@flightgear.org>

# (?x) sets the Python re.VERBOSE flag for the whole regular expression:
# https://docs.python.org/3/library/re.html#re.X
exclude: |
  (?x)^(3rdparty/|
        simgear/canvas/ShaderVG/|
        (.*/)? \.gitignore$)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt

  # check SPDX compliance
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file
